/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/EnvFinal.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Big_Screen.geometry} material={materials.Emissive} scale={[5.85, 5.81, 5.85]} />
      <mesh geometry={nodes.Blue_Wall.geometry} material={materials['Blue Wall_c']} position={[0, -0.1, 0]} />
      <mesh geometry={nodes.Ground.geometry} material={materials.Ground_c} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['VR Wall']} />
      <mesh geometry={nodes.Plane003_1.geometry} material={materials.Blue} />
      <group rotation={[-Math.PI, 0, 0]} scale={0}>
        <mesh geometry={nodes.picture.geometry} material={materials['draw.001']} position={[-473090.25, -29796.83, 219856.91]} rotation={[0, 0.06, 0]} />
        <mesh geometry={nodes.picture001.geometry} material={materials['draw.001']} position={[-407283.63, -29796.83, 325993.03]} rotation={[0, 0.06, 0]} />
        <mesh geometry={nodes.picture002.geometry} material={materials['draw.001']} position={[-318645.22, -29796.83, 414154.16]} rotation={[0, 0.01, 0]} />
        <mesh geometry={nodes.picture003.geometry} material={materials['draw.001']} position={[-230174.97, -29796.83, 478100.5]} rotation={[0, -0.16, 0]} />
      </group>
      <mesh geometry={nodes.Grass001.geometry} material={materials['Wood Grass_c']} position={[0, -0.13, 0]} />
      <mesh geometry={nodes.Grass002.geometry} material={materials['Wood Grass_c']} position={[0, -0.13, 0]} rotation={[0, -0.26, 0]} />
      <mesh geometry={nodes.Wood_Floor.geometry} material={materials['Wood Grass_c']} position={[22.92, 0, 17.7]} />
      <group position={[-1.31, 0, 17.5]}>
        <group position={[-20.19, 0, 4.18]}>
          <mesh geometry={nodes.pCube19.geometry} material={materials['Emissive.001']} position={[0, 4.78, 0]} rotation={[Math.PI, 0.71, 0]} />
          <mesh geometry={nodes.pPlane1.geometry} material={materials.ClassHubScreen_M1} position={[-7.79, 3.84, 2.12]} rotation={[2.54, 1.26, 0.58]} />
          <mesh geometry={nodes.pPlane1001.geometry} material={materials.ClassHubScreen_M1} position={[7.02, 3.84, 3.99]} rotation={[2.8, -1.02, -0.29]} />
          <mesh geometry={nodes.pPlane2.geometry} material={materials.ClassHubScreen_M2} position={[2.04, 3.81, 7.7]} rotation={[Math.PI / 2, 0, -1.3]} />
          <mesh geometry={nodes.pPlane2001.geometry} material={materials.ClassHubScreen_M2} position={[3.98, 3.81, -6.9]} rotation={[Math.PI / 2, 0, 2.62]} />
          <mesh geometry={nodes.pPlane3.geometry} material={materials.ClassHubScreen_M3} position={[7.59, 3.8, -1.94]} rotation={[Math.PI / 2, 0, -2.9]} />
          <mesh geometry={nodes.pPlane3001.geometry} material={materials.ClassHubScreen_M3} position={[-6.74, 3.8, -3.98]} rotation={[Math.PI / 2, 0, 1.02]} />
          <mesh geometry={nodes.pPlane4.geometry} material={materials['ClassHubScreen_M3.002']} position={[-2.34, 3.8, -7.46]} rotation={[Math.PI / 2, 0, 1.81]} />
          <mesh geometry={nodes.pPlane4001.geometry} material={materials['ClassHubScreen_M3.002']} position={[-3.6, 3.8, 6.94]} rotation={[Math.PI / 2, 0, -0.55]} />
        </group>
        <mesh geometry={nodes.ClassHub.geometry} material={materials.ClassHub_c} position={[-20.19, 0, 4.18]} rotation={[Math.PI / 2, 0, -1.8]} />
      </group>
      <mesh geometry={nodes.Logo_MetaStar.geometry} material={materials['Logo MetaStar_c']} position={[1.3, 6.81, -52.77]} rotation={[Math.PI / 2, 0, 0]} scale={35.93} />
      <mesh geometry={nodes.Logo001.geometry} material={materials.哈瑪星_LOGO} position={[6.75, 0.02, 27.58]} />
      <group position={[36.15, 11.44, -19.38]} rotation={[0, -0.23, 0]}>
        <mesh geometry={nodes.BezierCurve004.geometry} material={materials.Banner_c} />
        <mesh geometry={nodes.BezierCurve004_1.geometry} material={materials['Selling Curve']} />
      </group>
      <mesh geometry={nodes.Pillar001.geometry} material={materials.Banner_c} position={[28.77, 12.23, -34.51]} rotation={[0, -0.23, 0]} />
      <mesh geometry={nodes.Logo_Board.geometry} material={materials['Base pivit_c']} />
      <mesh geometry={nodes.Originate.geometry} material={materials['Base pivit_c']} />
      <mesh geometry={nodes.Originate_small.geometry} material={materials['Base pivit_c']} />
      <mesh geometry={nodes.VR_Wall.geometry} material={materials['Base pivit_c']} />
      <mesh geometry={nodes.DM001.geometry} material={materials.DM} />
      <mesh geometry={nodes.DM002.geometry} material={materials.DM} />
      <mesh geometry={nodes.w3.geometry} material={materials['Selling hub wall_c']} position={[43.68, 4.13, -20.31]} rotation={[0, -0.23, 0]} scale={0.01}>
        <mesh geometry={nodes.SellingScreen.geometry} material={nodes.SellingScreen.material} />
      </mesh>
      <group position={[-51.34, 10.45, 12.23]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.ScreenReal002_1.geometry} material={materials.ScreenBake} />
        <mesh geometry={nodes.ScreenReal002_2.geometry} material={materials['Screen 75x25x225']} />
      </group>
      <mesh geometry={nodes.Autostereoscopic_3D.geometry} material={materials.ScreenBase_c} position={[-30.39, 0, -13.46]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.ScreenBase002.geometry} material={materials.ScreenBase_c} position={[-1672.59, 1329.18, -112.68]}>
          <mesh geometry={nodes.Screen_A1.geometry} material={materials['Screen 3x7x6.001']} />
          <mesh geometry={nodes.Screen_A1_1.geometry} material={materials.Wall} />
        </mesh>
      </mesh>
      <group position={[15, 0, 0]}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['VR Wall.002']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Grass.002']} />
        <mesh geometry={nodes.tree001.geometry} material={materials['Tree.001']}>
          <mesh geometry={nodes.Photo_Leaves.geometry} material={materials['Sky City']} position={[0, 11.53, 0]} />
          <mesh geometry={nodes.Photo_Leaves001.geometry} material={materials['Tree Colorful']} position={[0, 11.53, 0]} rotation={[-Math.PI, 0.44, -Math.PI]} scale={0.93} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/EnvFinal.glb')
