/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function ModelC({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/m.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="root" scale={0.01}>
          <primitive object={nodes.rootx} />
          <skinnedMesh name="Body" geometry={nodes.Body.geometry} material={materials['Ch Body']} skeleton={nodes.Body.skeleton} />
          <group name="Cloth_6_Star">
            <skinnedMesh name="Cloth_6_Star_1" geometry={nodes.Cloth_6_Star_1.geometry} material={materials['Hat Star']} skeleton={nodes.Cloth_6_Star_1.skeleton} />
            <skinnedMesh name="Cloth_6_Star_2" geometry={nodes.Cloth_6_Star_2.geometry} material={materials['Star Jacket']} skeleton={nodes.Cloth_6_Star_2.skeleton} />
          </group>
          <group name="Face">
            <skinnedMesh name="Face_1" geometry={nodes.Face_1.geometry} material={materials['Ch Body']} skeleton={nodes.Face_1.skeleton} />
            <skinnedMesh name="Face_2" geometry={nodes.Face_2.geometry} material={materials['Ch Face']} skeleton={nodes.Face_2.skeleton} />
          </group>
          <skinnedMesh name="Pants_2_Star" geometry={nodes.Pants_2_Star.geometry} material={materials['Hat Star']} skeleton={nodes.Pants_2_Star.skeleton} />
          <skinnedMesh name="Shoes_2_Star" geometry={nodes.Shoes_2_Star.geometry} material={materials['Hat Star']} skeleton={nodes.Shoes_2_Star.skeleton} />
          <skinnedMesh name="ToothTop" geometry={nodes.ToothTop.geometry} material={materials['Ch Body']} skeleton={nodes.ToothTop.skeleton} />
          <skinnedMesh name="ToothTop002" geometry={nodes.ToothTop002.geometry} material={materials['Ch Body']} skeleton={nodes.ToothTop002.skeleton} />
          <skinnedMesh name="Tune" geometry={nodes.Tune.geometry} material={materials['Ch Body']} skeleton={nodes.Tune.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/m.glb')
