/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Env2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.DM001.geometry} material={materials.DM} />
      <mesh geometry={nodes.DM002.geometry} material={materials.DM} />
      <mesh geometry={nodes.Big_Screen.geometry} material={materials.Emissive} scale={[5.85, 5.81, 5.85]} />
      <group position={[0, -0.1, 0]}>
        <mesh geometry={nodes.Cube.geometry} material={materials['VR Wall']} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Light Orange']} />
      </group>
      <mesh geometry={nodes.Ground.geometry} material={materials['VR Wall']} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['VR Wall']} />
      <mesh geometry={nodes.Plane003_1.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Wood_Floor.geometry} material={nodes.Wood_Floor.material} position={[22.92, 0, 17.7]} />
      <group rotation={[-Math.PI, 0, 0]} scale={0}>
        <mesh geometry={nodes.picture.geometry} material={materials['draw.001']} position={[-473090.25, -28567.65, 219856.91]} rotation={[0, 0.06, 0]} />
        <mesh geometry={nodes.picture001.geometry} material={materials['draw.001']} position={[-407283.63, -28567.65, 325993.03]} rotation={[0, 0.06, 0]} />
        <mesh geometry={nodes.picture002.geometry} material={materials['draw.001']} position={[-318645.22, -28567.65, 414154.16]} rotation={[0, 0.01, 0]} />
        <mesh geometry={nodes.picture003.geometry} material={materials['draw.001']} position={[-230174.97, -28567.65, 478100.5]} rotation={[0, -0.16, 0]} />
      </group>
      <mesh geometry={nodes.Circle003.geometry} material={materials['VR Wall']} />
      <mesh geometry={nodes.Circle003_1.geometry} material={materials.Gold} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['VR Wall']} />
      <mesh geometry={nodes.Cylinder006_1.geometry} material={materials.Gold} />
      <mesh geometry={nodes.Circle001.geometry} material={materials['VR Wall']} />
      <mesh geometry={nodes.Circle001_1.geometry} material={materials.Gold} />
      <mesh geometry={nodes.Circle016.geometry} material={materials['VR Wall']} />
      <mesh geometry={nodes.Circle016_1.geometry} material={materials.Gold} />
      <group position={[36.15, 11.44, -19.38]} rotation={[0, -0.23, 0]}>
        <mesh geometry={nodes.BezierCurve004.geometry} material={materials['Orange.002']} />
        <mesh geometry={nodes.BezierCurve004_1.geometry} material={materials['Selling Curve']} />
      </group>
      <group position={[0, -0.13, 0]}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials.Grass} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['VR Wall']} />
      </group>
      <group position={[0, -0.13, 0]} rotation={[0, -0.26, 0]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.Grass} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['VR Wall']} />
      </group>
      <group position={[28.77, 12.23, -34.51]} rotation={[0, -0.23, 0]}>
        <mesh geometry={nodes.Cylinder007.geometry} material={materials['VR Wall.003']} />
        <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['Light White']} />
        <mesh geometry={nodes.Cylinder007_2.geometry} material={materials['Grass.003']} />
      </group>
      <group position={[-1.31, 0, 17.5]}>
        <mesh geometry={nodes.Chairs.geometry} material={materials['Class_M.001']} position={[-20.19, 0, 4.18]} rotation={[Math.PI / 2, 0, -1.8]} />
        <mesh geometry={nodes.pCube1.geometry} material={materials['Class_M.001']} position={[-11.9, 1.75, 2.11]} rotation={[1.57, 0, -0.24]}>
          <mesh geometry={nodes.pPlane3.geometry} material={materials.ClassHubScreen_M3} position={[-0.72, -0.04, -2.05]} rotation={[0, 0, -2.65]} />
        </mesh>
        <mesh geometry={nodes.pCube1001.geometry} material={materials['Class_M.001']} position={[-27.53, 1.75, -0.19]} rotation={[1.57, 0, -2.6]}>
          <mesh geometry={nodes.pPlane3001.geometry} material={materials.ClassHubScreen_M3} position={[-0.72, -0.04, -2.05]} rotation={[0, 0, -2.65]} />
        </mesh>
        <mesh geometry={nodes.pCube19.geometry} material={materials['Emissive.001']} position={[-20.19, 4.78, 4.18]} rotation={[Math.PI, 0.71, 0]} />
        <mesh geometry={nodes.pCube2.geometry} material={materials['Class_M.001']} position={[-20.19, -0.04, 4.18]} rotation={[Math.PI / 2, 0, -1.8]} />
        <mesh geometry={nodes.pCube20.geometry} material={materials['Class_M.001']} position={[-22.77, 1.75, -3.96]} rotation={[1.57, 0, -1.88]}>
          <mesh geometry={nodes.pPlane4.geometry} material={materials['ClassHubScreen_M3.002']} position={[-0.73, 0.02, -2.05]} rotation={[0, 0, -2.59]} />
        </mesh>
        <mesh geometry={nodes.pCube20001.geometry} material={materials['Class_M.001']} position={[-24.11, 1.75, 11.78]} rotation={[1.57, 0, 2.05]}>
          <mesh geometry={nodes.pPlane4001.geometry} material={materials['ClassHubScreen_M3.002']} position={[-0.73, 0.02, -2.05]} rotation={[0, 0, -2.59]} />
        </mesh>
        <mesh geometry={nodes.pCube21.geometry} material={materials['Class_M.001']} position={[-28.45, 1.77, 6.39]} rotation={[1.57, 0, 2.88]}>
          <mesh geometry={nodes.pPlane1.geometry} material={materials.ClassHubScreen_M1} position={[-0.47, -0.03, -2.07]} rotation={[0, -1.4, -1.57]} />
        </mesh>
        <mesh geometry={nodes.pCube21001.geometry} material={materials['Class_M.001']} position={[-12.78, 1.77, 8.44]} rotation={[1.57, 0, 0.52]}>
          <mesh geometry={nodes.pPlane1001.geometry} material={materials.ClassHubScreen_M1} position={[-0.47, -0.03, -2.07]} rotation={[0, -1.4, -1.57]} />
        </mesh>
        <mesh geometry={nodes.pCube22.geometry} material={materials['Class_M.001']} position={[-18.06, 1.77, 12.46]} rotation={[1.57, 0, 1.32]}>
          <mesh geometry={nodes.pPlane2.geometry} material={materials.ClassHubScreen_M2} position={[-0.57, -0.06, -2.04]} rotation={[0, 0, -2.62]} />
        </mesh>
        <mesh geometry={nodes.pCube22001.geometry} material={materials['Class_M.001']} position={[-15.87, 1.77, -3.19]} rotation={[1.57, 0, -1.04]}>
          <mesh geometry={nodes.pPlane2001.geometry} material={materials.ClassHubScreen_M2} position={[-0.57, -0.06, -2.04]} rotation={[0, 0, -2.62]} />
        </mesh>
        <mesh geometry={nodes.pCube3.geometry} material={materials['Class_M.001']} position={[-20.19, -0.04, 4.18]} rotation={[Math.PI / 2, 0, -1.01]} />
        <mesh geometry={nodes.pCube4.geometry} material={materials['Class_M.001']} position={[-20.19, -0.04, 4.18]} rotation={[Math.PI / 2, 0, -0.22]} />
        <mesh geometry={nodes.pCube5.geometry} material={materials['Class_M.001']} position={[-20.19, -0.04, 4.18]} rotation={[Math.PI / 2, 0, 0.56]} />
        <mesh geometry={nodes.pCube6.geometry} material={materials['Class_M.001']} position={[-20.19, -0.04, 4.18]} rotation={[Math.PI / 2, 0, 1.35]} />
        <mesh geometry={nodes.pCube7.geometry} material={materials['Class_M.001']} position={[-20.19, -0.04, 4.18]} rotation={[Math.PI / 2, 0, 2.13]} />
        <mesh geometry={nodes.pCube8.geometry} material={materials['Class_M.001']} position={[-20.19, -0.04, 4.18]} rotation={[Math.PI / 2, 0, 2.92]} />
        <mesh geometry={nodes.pCube9004.geometry} material={materials['Class_M.001']} position={[-20.19, -0.04, 4.18]} rotation={[Math.PI / 2, 0, -2.58]} />
        <mesh geometry={nodes.pCylinder2.geometry} material={materials['Class_M.001']} position={[-20.19, 0, 4.18]} rotation={[Math.PI / 2, 0, -1.8]} />
        <mesh geometry={nodes.pCylinder28.geometry} material={materials['Class_M.001']} position={[-20.19, 1.67, 4.18]} rotation={[Math.PI / 2, 0, -1.8]} />
        <mesh geometry={nodes.pCylinder29.geometry} material={materials['Class_M.001']} position={[-23.23, 0.31, -9.08]} rotation={[Math.PI / 2, 0, -1.8]} />
        <mesh geometry={nodes.pCylinder30.geometry} material={materials['Class_M.001']} position={[-33.52, 0.31, 6.96]} rotation={[Math.PI / 2, 0, 2.94]} />
        <mesh geometry={nodes.pCylinder31.geometry} material={materials['Class_M.001']} position={[-17.68, 0.31, 17.56]} rotation={[Math.PI / 2, 0, 1.38]} />
        <mesh geometry={nodes.pCylinder32.geometry} material={materials['Class_M.001']} position={[-6.77, 0.31, 1.93]} rotation={[Math.PI / 2, 0, -0.17]} />
        <mesh geometry={nodes.pCylinder4.geometry} material={materials['Class_M.001']} position={[-20.19, -38.39, 4.18]} rotation={[Math.PI / 2, 0, -1.8]} />
        <mesh geometry={nodes.polySurface10.geometry} material={materials['Class_M.001']} position={[-17.55, 0, 4.47]} rotation={[Math.PI / 2, 0, -1.5]} />
        <mesh geometry={nodes.polySurface18.geometry} material={materials['Class_M.001']} position={[-19.83, 0, 1.55]} rotation={[Math.PI / 2, 0, -3.04]} />
        <mesh geometry={nodes.polySurface19.geometry} material={materials['Class_M.001']} position={[-22.81, 0, 3.72]} rotation={[Math.PI / 2, 0, 1.71]} />
        <mesh geometry={nodes.polySurface20.geometry} material={materials['Class_M.001']} position={[-20.64, -0.05, 6.8]} rotation={[1.59, 0, 0.13]} />
      </group>
      <mesh geometry={nodes.Logo.geometry} material={materials.哈瑪星_LOGO} position={[6.75, 0.89, 27.58]} />
      <group position={[1.3, 6.81, -53.05]} rotation={[Math.PI / 2, 0, 0]} scale={35.93}>
        <mesh geometry={nodes.Curve064.geometry} material={materials.M} />
        <mesh geometry={nodes.Curve064_1.geometry} material={materials.S} />
        <mesh geometry={nodes.Curve064_2.geometry} material={materials.W} />
      </group>
      <mesh geometry={nodes.w3.geometry} material={materials['Selling hub wall']} position={[43.68, 4.13, -20.31]} rotation={[0, -0.23, 0]} scale={0.01}>
        <mesh geometry={nodes.SellingScreen.geometry} material={materials['Selling Screen']} position={[-2.19, 0, 1.82]} />
      </mesh>
      <group position={[-30.39, 0, -13.46]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.PillarM.geometry} material={materials.Orange} />
        <mesh geometry={nodes.PillarM_1.geometry} material={materials.sideLing_02} />
        <mesh geometry={nodes.ScreenBase002.geometry} material={materials['Orange.001']} position={[-1672.59, 1329.18, -112.68]}>
          <mesh geometry={nodes.Screen_A1.geometry} material={materials['Screen 3x7x6.001']} />
          <mesh geometry={nodes.Screen_A1_1.geometry} material={materials.Wall} />
        </mesh>
        <group position={[-2094.76, 2569.2, -1045.09]}>
          <mesh geometry={nodes.ScreenReal002_1.geometry} material={materials['ScreenBake.001']} />
          <mesh geometry={nodes.ScreenReal002_2.geometry} material={materials['Screen 75x25x225.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Env2.glb')
